// Generado desde el CSV — 60 productos Saint Gobain comercializados por HP Templados
window.PRODUCTOS = [
  {
    "nombre": "COOL-LITE ST 108",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar extremo, color neutro. TL=9%, SHGC=0.18. Alta reflectividad 43%.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro",
    "tl": 9,
    "shgc": 0.18,
    "sc": 0.21,
    "sel": 0.5,
    "u": "3.7 inv / 2.8 ver",
    "ref_ext": 43,
    "ref_int": 34,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas y edificios comerciales; edificios industriales; hoteles; escuelas y hospitales",
    "beneficios": "Máximo bloqueo solar; alta reflectividad; privacidad diurna total; reduce consumo AC",
    "necesidad": "Fachada con máxima protección solar donde la baja transmisión de luz es aceptable o deseada",
    "pitch": "Cuando el proyecto requiere el máximo rechazo solar con estética de espejo. Ideal para torres de oficinas con alta exposición solar.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. U-inv=3.7, U-ver=2.8 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 308",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar extremo, color gris. TL=4%, SHGC=0.24. Reflectividad 13%.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Gris",
    "tl": 4,
    "shgc": 0.24,
    "sc": 0.27,
    "sel": 0.17,
    "u": "3.7 inv / 2.8 ver",
    "ref_ext": 13,
    "ref_int": 34,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; edificios industriales; hoteles",
    "beneficios": "Máximo bloqueo solar; estética gris discreta; baja reflexión exterior; reduce consumo AC",
    "necesidad": "Fachada con máxima protección solar y estética gris en lugar de reflectiva",
    "pitch": "Para proyectos donde se quiere máxima protección solar con apariencia más discreta y menos reflectiva que el neutro.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. Selectividad 0.17 muy baja (alta absorción de calor).",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 408",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar extremo, color verde. TL=7%, SHGC=0.24. Reflectividad 30%.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Verde",
    "tl": 7,
    "shgc": 0.24,
    "sc": 0.28,
    "sel": 0.29,
    "u": "3.7 inv / 2.8 ver",
    "ref_ext": 30,
    "ref_int": 34,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; edificios industriales; hoteles; centros comerciales",
    "beneficios": "Máximo bloqueo solar; estética verde; reflexión exterior media; reduce consumo AC",
    "necesidad": "Fachada con máxima protección solar y tono verde que armoniza con entornos naturales",
    "pitch": "Combinación de máxima protección solar con tonalidad verde. Ideal para proyectos arquitectónicos con concepto ecológico.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 120",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Alto control solar, color neutro. TL=21%, SHGC=0.34. Balance control/visibilidad.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro",
    "tl": 21,
    "shgc": 0.34,
    "sc": 0.39,
    "sel": 0.62,
    "u": "5.2 inv / 4.6 ver",
    "ref_ext": 32,
    "ref_int": 26,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; centros comerciales; hoteles; hospitales; escuelas",
    "beneficios": "Alto control solar; buena visibilidad hacia afuera; reduce consumo AC; confort en verano",
    "necesidad": "Fachada que necesita control solar importante con algo de visibilidad natural y vista exterior",
    "pitch": "El balance ideal para edificios de oficinas: buen rechazo solar con visibilidad hacia afuera. Mayor selectividad que la serie 08.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 320",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Alto control solar, color gris. TL=10%, SHGC=0.35.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Gris",
    "tl": 10,
    "shgc": 0.35,
    "sc": 0.4,
    "sel": 0.29,
    "u": "5.2 inv / 4.6 ver",
    "ref_ext": 11,
    "ref_int": 26,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; centros comerciales; hoteles",
    "beneficios": "Alto control solar; estética gris; baja reflexión exterior; reduce consumo AC",
    "necesidad": "Fachada gris con buen control solar sin efecto espejo pronunciado",
    "pitch": "Para diseños arquitectónicos que requieren estética gris elegante con buen desempeño solar.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. Baja selectividad (0.29).",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 420",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Alto control solar, color verde. TL=17%, SHGC=0.35.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Verde",
    "tl": 17,
    "shgc": 0.35,
    "sc": 0.4,
    "sel": 0.49,
    "u": "5.2 inv / 4.6 ver",
    "ref_ext": 23,
    "ref_int": 26,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; centros comerciales; hoteles; naves industriales",
    "beneficios": "Alto control solar; estética verde; reflexión media; reduce consumo AC",
    "necesidad": "Fachada verde con alto rechazo solar para climas soleados",
    "pitch": "Combina tono verde con alto rechazo solar. Excelente para proyectos con identidad visual verde.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 136",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar medio-alto, color neutro. TL=37%, SHGC=0.47. Buena luz natural.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro",
    "tl": 37,
    "shgc": 0.47,
    "sc": 0.54,
    "sel": 0.79,
    "u": "5.6 inv / 5.0 ver",
    "ref_ext": 22,
    "ref_int": 18,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas y edificios comerciales; hoteles; restaurantes; escuelas; hospitales",
    "beneficios": "Buen control solar; buena luz natural; confort visual; reduce consumo AC",
    "necesidad": "Fachada que necesita equilibrio entre control solar y entrada de luz natural",
    "pitch": "El equilibrio perfecto: protección solar significativa con buena iluminación natural. Muy popular en oficinas modernas.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. Selectividad 0.79.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 336",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar medio-alto, color gris. TL=18%, SHGC=0.42.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Gris",
    "tl": 18,
    "shgc": 0.42,
    "sc": 0.49,
    "sel": 0.43,
    "u": "5.6 inv / 5.0 ver",
    "ref_ext": 8,
    "ref_int": 18,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; hoteles; centros comerciales",
    "beneficios": "Buen control solar; estética gris; baja reflexión; reduce consumo AC",
    "necesidad": "Fachada gris con buen balance control solar / visibilidad",
    "pitch": "Estética gris sobria con desempeño solar competente. Baja reflectividad exterior (8%) muy elegante.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 436",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar medio-alto, color verde. TL=30%, SHGC=0.41.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Verde",
    "tl": 30,
    "shgc": 0.41,
    "sc": 0.47,
    "sel": 0.73,
    "u": "5.6 inv / 5.0 ver",
    "ref_ext": 16,
    "ref_int": 18,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; hoteles; centros comerciales; escuelas",
    "beneficios": "Buen control solar; estética verde; buena luz natural; reduce consumo AC",
    "necesidad": "Fachada verde con control solar y buena visibilidad",
    "pitch": "Tonalidad verde natural con buen desempeño solar. Visibilidad interior-exterior satisfactoria.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. Selectividad 0.73.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 150",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar medio, color neutro. TL=51%, SHGC=0.58. Alta luz natural.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro",
    "tl": 51,
    "shgc": 0.58,
    "sc": 0.67,
    "sel": 0.88,
    "u": "5.7 inv / 5.2 ver",
    "ref_ext": 18,
    "ref_int": 17,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; edificios comerciales; hoteles; restaurantes",
    "beneficios": "Buena entrada de luz natural; control solar moderado; aspecto casi transparente; reduce consumo AC",
    "necesidad": "Fachada que prioriza la entrada de luz pero necesita algo de control solar",
    "pitch": "Alta transmisión de luz con protección solar moderada. Para arquitectos que no quieren oscurecer el espacio pero sí controlar el calor.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 350",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar medio, color gris. TL=24%, SHGC=0.48.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Gris",
    "tl": 24,
    "shgc": 0.48,
    "sc": 0.55,
    "sel": 0.5,
    "u": "5.7 inv / 5.2 ver",
    "ref_ext": 7,
    "ref_int": 16,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; hoteles; centros comerciales",
    "beneficios": "Control solar moderado; estética gris refinada; reflexión muy baja (7%); reduce consumo AC",
    "necesidad": "Fachada gris con buena apariencia y control solar moderado",
    "pitch": "Gris elegante con reflexión exterior mínima (7%). Para edificios donde se quiere discreción visual y un buen desempeño térmico.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 450",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar medio, color verde. TL=41%, SHGC=0.46.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y de oficinas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Verde",
    "tl": 41,
    "shgc": 0.46,
    "sc": 0.53,
    "sel": 0.89,
    "u": "5.7 inv / 5.2 ver",
    "ref_ext": 13,
    "ref_int": 17,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; hoteles; escuelas; restaurantes",
    "beneficios": "Buena luz natural; estética verde; control solar moderado; selectividad alta para su color",
    "necesidad": "Fachada verde con mucha luz natural y control solar moderado",
    "pitch": "Verde con alta transmisión de luz y muy buena selectividad (0.89). Para proyectos que requieren iluminación natural con tono verde.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. Mejor selectividad de la serie verde.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 167",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar básico, color neutro. TL=66%, SHGC=0.70. Casi transparente.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y ventanas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro",
    "tl": 66,
    "shgc": 0.7,
    "sc": 0.8,
    "sel": 0.94,
    "u": "5.7 inv / 5.2 ver",
    "ref_ext": 19,
    "ref_int": 19,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; edificios comerciales; residencias; ventanas",
    "beneficios": "Alta transmisión de luz; casi transparente; algo de control solar; neutro perfecto",
    "necesidad": "Ventana o fachada que necesita máxima visibilidad con algún control solar mínimo",
    "pitch": "Para cuando necesitas casi toda la luz natural posible pero quieres algo de protección solar. Excelente para residencias de lujo con grandes ventanales.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. TL muy alto para un vidrio de control solar.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 367",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Control solar básico, color gris. TL=32%, SHGC=0.54.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y ventanas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Gris",
    "tl": 32,
    "shgc": 0.54,
    "sc": 0.62,
    "sel": 0.59,
    "u": "5.7 inv / 5.2 ver",
    "ref_ext": 8,
    "ref_int": 17,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; hoteles; centros comerciales",
    "beneficios": "Control solar moderado; estética gris natural; baja reflexión; filtro solar básico",
    "necesidad": "Fachada gris con buen nivel de luz y control solar moderado",
    "pitch": "Gris claro con baja reflexión. Aspecto natural y discreto con protección solar competente.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE ST 467",
    "familia": "Cool-Lite ST",
    "slug": "cool-lite-st",
    "desc": "Alta transmisión, color verde. TL=54%, SHGC=0.50. Mayor selectividad serie verde.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas comerciales y ventanas",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Verde",
    "tl": 54,
    "shgc": 0.5,
    "sc": 0.58,
    "sel": 1.08,
    "u": "5.7 inv / 5.2 ver",
    "ref_ext": 14,
    "ref_int": 18,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de oficinas; residencias; hoteles; escuelas",
    "beneficios": "Alta luz natural; color verde elegante; selectividad >1; buen control solar; reduce consumo AC",
    "necesidad": "Fachada verde con máxima luminosidad y excelente selectividad",
    "pitch": "El modelo verde más selectivo (Sel=1.08 >1). Alta transmisión de luz con buen control solar. Ideal para proyectos arquitectónicos con fachadas verdes luminosas.",
    "notas": "Valor monolítico 6mm cara #2 según NFRC. Único ST con selectividad >1.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-st"
  },
  {
    "nombre": "COOL-LITE KNT 164",
    "familia": "Cool-Lite KNT",
    "slug": "cool-lite-knt",
    "desc": "Low-E + control solar, selectividad alta. TL=58%, g=0.46, U_aire=1.9.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas con aislamiento térmico y control solar",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro (tonalidad gris-azul)",
    "tl": 58,
    "shgc": 0.46,
    "sc": 0.53,
    "sel": 1.26,
    "u": "1.9 aire / 1.6 argon",
    "ref_ext": 14,
    "ref_int": 10,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas; centros comerciales; hospitales; colegios; naves industriales; viviendas",
    "beneficios": "Alto aislamiento térmico; control solar; alta selectividad (1.26); alta transmisión luz; bajo U-value",
    "necesidad": "Fachada que necesita tanto control solar como buen aislamiento térmico en climas calurosos y fríos",
    "pitch": "La solución premium DGU cuando la eficiencia energética integral es la prioridad. U=1.9 + selectividad 1.26 es difícil de superar.",
    "notas": "DGU 6+12Aire+6mm, EN410. Capa en superficie #2. U argon=1.6 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-knt"
  },
  {
    "nombre": "COOL-LITE KNT 155",
    "familia": "Cool-Lite KNT",
    "slug": "cool-lite-knt",
    "desc": "Low-E + control solar, TL=47%, g=0.37, U_aire=1.8. Balance óptimo.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas con aislamiento térmico y control solar",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro (tonalidad gris-azul)",
    "tl": 47,
    "shgc": 0.37,
    "sc": 0.43,
    "sel": 1.27,
    "u": "1.8 aire / 1.5 argon",
    "ref_ext": 17,
    "ref_int": 10,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas; centros comerciales; hospitales; colegios; naves industriales; viviendas",
    "beneficios": "Muy alto aislamiento térmico (U=1.8); buen control solar; alta selectividad; reduce AC y calefacción",
    "necesidad": "Fachada que necesita máximo control solar y excelente aislamiento térmico",
    "pitch": "Mejor U-value que KNT 164 con muy buena selectividad. Ideal para proyectos con certificación energética exigente.",
    "notas": "DGU 6+12Aire+6mm, EN410. Selectividad 1.27, la más alta de la gama KNT. U argon=1.5.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-knt"
  },
  {
    "nombre": "COOL-LITE KNT 140",
    "familia": "Cool-Lite KNT",
    "slug": "cool-lite-knt",
    "desc": "Low-E control solar intenso. TL=37%, g=0.29, U_aire=1.8. Alta protección solar.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas con aislamiento térmico y control solar",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro (tonalidad gris-azul)",
    "tl": 37,
    "shgc": 0.29,
    "sc": 0.33,
    "sel": 1.28,
    "u": "1.8 aire / 1.5 argon",
    "ref_ext": 23,
    "ref_int": 12,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas; centros comerciales; hospitales; colegios; naves industriales",
    "beneficios": "Muy alto aislamiento (U=1.8); máximo rechazo solar (g=0.29); alta selectividad (1.28)",
    "necesidad": "Fachada en clima muy caluroso que necesita máxima protección solar con bajo U-value",
    "pitch": "Para climas extremos: máximo rechazo solar (g=0.29) con excelente aislamiento térmico (U=1.8). La mejor protección contra el calor en la gama KNT.",
    "notas": "DGU 6+12Aire+6mm, EN410. SC=0.33 (sitio web muestra 1.33 por error tipográfico). U argon=1.5.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-knt"
  },
  {
    "nombre": "COOL-LITE KBT 140",
    "familia": "Cool-Lite KNT",
    "slug": "cool-lite-knt",
    "desc": "Low-E control solar, variante KBT. TL=36%, g=0.30, U_aire=1.8.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas con aislamiento térmico y control solar",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro (tonalidad gris-azul)",
    "tl": 36,
    "shgc": 0.3,
    "sc": 0.35,
    "sel": 1.2,
    "u": "1.8 aire / 1.5 argon",
    "ref_ext": 24,
    "ref_int": 17,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas; centros comerciales; hospitales; colegios; naves industriales",
    "beneficios": "Muy alto aislamiento (U=1.8); alto rechazo solar; variante KBT con mayor reflexión interior",
    "necesidad": "Fachada con necesidad de control solar máximo, mayor privacidad hacia el interior",
    "pitch": "Similar al KNT 140 pero con mayor reflexión interior (17%), lo que brinda más privacidad desde afuera hacia adentro.",
    "notas": "DGU 6+12Aire+6mm, EN410. SC=0.35 (sitio web muestra 2.34 por error tipográfico). U argon=1.5. LRi=17% vs 12% del KNT 140.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-knt"
  },
  {
    "nombre": "COOL-LITE SK 138 II",
    "familia": "Cool-Lite KS",
    "slug": "cool-lite-ks",
    "desc": "Alto desempeño, estética incomparable. TL=36%, SHGC=0.25, U_inv=1.7. Selectividad 1.44.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con alta eficiencia energética",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro",
    "tl": 36,
    "shgc": 0.25,
    "sc": 0.29,
    "sel": 1.44,
    "u": "1.7 inv / 1.6 ver",
    "ref_ext": 38,
    "ref_int": 20,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas premium; centros comerciales; hospitales; hoteles; edificios corporativos",
    "beneficios": "Excelente aislamiento térmico (U=1.7); alta selectividad (1.44); máximo rechazo solar; alta reflexión exterior 38%",
    "necesidad": "Fachada de alto desempeño con estética de alta reflexión y máxima eficiencia energética",
    "pitch": "Cuando el proyecto requiere el mejor desempeño energético posible con estética de alta gama. U=1.7 + selectividad 1.44 es de clase mundial.",
    "notas": "DGU 6+12Aire+6mm, NFRC. LRe=38% da aspecto muy reflectivo. Ug ver=1.6 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-ks"
  },
  {
    "nombre": "COOL-LITE SK 154 II",
    "familia": "Cool-Lite KS",
    "slug": "cool-lite-ks",
    "desc": "Alto desempeño, mayor luz. TL=50%, SHGC=0.33, U_inv=1.7. Selectividad 1.52.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con alta eficiencia energética",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100",
    "color": "Neutro",
    "tl": 50,
    "shgc": 0.33,
    "sc": 0.38,
    "sel": 1.52,
    "u": "1.7 inv / 1.6 ver",
    "ref_ext": 29,
    "ref_int": 17,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas premium; centros comerciales; hospitales; hoteles; edificios corporativos",
    "beneficios": "Excelente aislamiento térmico (U=1.7); máxima selectividad serie KS (1.52); alta luz natural; bajo reflejo",
    "necesidad": "Fachada que necesita alta eficiencia energética con buena entrada de luz natural",
    "pitch": "La mejor selectividad de la gama KS (1.52). Alta transmisión de luz (50%) con excelente control solar. Para edificios que quieren certificación LEED/BREEAM.",
    "notas": "DGU 6+12Aire+6mm, NFRC. Mayor TL y selectividad que SK 138 II. Ug ver=1.6 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-ks"
  },
  {
    "nombre": "COOL-LITE SKN 146 II",
    "familia": "Cool-Lite SKN",
    "slug": "cool-lite-skn",
    "desc": "Neutro, eficiente, bajo U-value. TL=40%, SHGC=0.25, U_inv=1.7. Selectividad 1.60.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas con neutralidad estética y alta eficiencia",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Neutro",
    "tl": 40,
    "shgc": 0.25,
    "sc": 0.28,
    "sel": 1.6,
    "u": "1.7 inv / 1.6 ver",
    "ref_ext": 43,
    "ref_int": 11,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas; centros comerciales; hospitales; colegios; naves industriales; viviendas; hoteles",
    "beneficios": "Alta reflexión exterior (43%); bajo U-value (1.7); alta selectividad (1.60); aspecto espejo; bajo U-value",
    "necesidad": "Fachada neutra, elegante y altamente eficiente con aspecto espejo de alta calidad",
    "pitch": "SKN 146 II: el más oscuro de la serie, alta reflexión (43%) con excelente selectividad. Para fachadas que quieren aspecto de espejo con máxima eficiencia energética.",
    "notas": "DGU 6+12Aire+6mm, capa cara #2, NFRC. Dimensión estándar disponible en 3.30x2.60m y 3.30x6.10m.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-skn"
  },
  {
    "nombre": "COOL-LITE SKN 154 II",
    "familia": "Cool-Lite SKN",
    "slug": "cool-lite-skn",
    "desc": "Neutro eficiente, selectividad excepcional. TL=51%, SHGC=0.27, U_inv=1.6. Selectividad 1.89.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas con neutralidad estética y alta eficiencia",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Neutro",
    "tl": 51,
    "shgc": 0.27,
    "sc": 0.31,
    "sel": 1.89,
    "u": "1.6 inv / 1.5 ver",
    "ref_ext": 18,
    "ref_int": 22,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas; centros comerciales; hospitales; colegios; naves industriales; viviendas; hoteles",
    "beneficios": "Selectividad muy alta (1.89); bajo U-value (1.6); excelente transmisión de luz; eficiencia energética premium",
    "necesidad": "Fachada que necesita máxima eficiencia energética con alta transmisión de luz y apariencia neutra",
    "pitch": "La mejor relación selectividad/transmisión de la serie SKN. TL=51% con g=0.27 es extraordinario. Para edificios Net-Zero o certificaciones LEED Platinum.",
    "notas": "DGU 6+12Aire+6mm, capa cara #2, NFRC. U ver=1.5 W/m²K con argon.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-skn"
  },
  {
    "nombre": "COOL-LITE SKN 176 II",
    "familia": "Cool-Lite SKN",
    "slug": "cool-lite-skn",
    "desc": "Neutro de alta transmisión. TL=68%, SHGC=0.34, U_inv=1.6. Selectividad 2.00.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas con neutralidad estética y alta eficiencia",
    "configuracion": "DGU (6+12Aire+6mm)",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Neutro",
    "tl": 68,
    "shgc": 0.34,
    "sc": 0.39,
    "sel": 2,
    "u": "1.6 inv / 1.5 ver",
    "ref_ext": 13,
    "ref_int": 15,
    "norma": "NFRC",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Fachadas; centros comerciales; hospitales; colegios; naves industriales; viviendas; hoteles",
    "beneficios": "Selectividad máxima de la serie (2.00); TL altísimo (68%); bajo U-value (1.6); aspecto casi transparente",
    "necesidad": "Fachada casi transparente con la mejor selectividad posible y bajo U-value",
    "pitch": "El SKN más avanzado: selectividad 2.00 con TL=68%. Para edificios que quieren ser muy luminosos sin sacrificar eficiencia energética. El \"vidrio invisible eficiente\".",
    "notas": "DGU 6+12Aire+6mm, capa cara #2, NFRC. Selectividad=2.00, referencia de clase mundial. U ver=1.5 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-skn"
  },
  {
    "nombre": "COOL-LITE XTREME 60/28",
    "familia": "Cool-Lite Xtreme",
    "slug": "cool-lite-xtreme",
    "desc": "Selectividad extrema (2.11). TL=59%, g=0.28. Primera generación.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con selectividad extrema",
    "configuracion": "DGU",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro",
    "tl": 59,
    "shgc": 0.28,
    "sc": 0.33,
    "sel": 2.11,
    "u": "1.5 aire / 1.2 argon",
    "ref_ext": 14,
    "ref_int": 17,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "ES_DGU",
    "aplicaciones": "Edificios de oficinas; centros comerciales; residencias de lujo; hoteles; restaurantes; escuelas; hospitales",
    "beneficios": "Selectividad extrema (2.11); máximo control solar (g=0.28); alta luz natural (59%); bajo U-value (1.5)",
    "necesidad": "Fachada de alta gama que necesita el máximo rechazo solar con la mayor entrada de luz posible",
    "pitch": "XTREME 60/28: la versión original. Cuando quieres dejar entrar mucha luz (59%) pero bloqueando casi toda la energía solar (g=0.28). Selectividad 2.11 es excepcional.",
    "notas": "DGU, EN410. U argon=1.2 W/m²K. Puede ser templado.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-xtreme"
  },
  {
    "nombre": "COOL-LITE XTREME 60/28 II",
    "familia": "Cool-Lite Xtreme",
    "slug": "cool-lite-xtreme",
    "desc": "Selectividad extrema gen.2 (2.14). TL=60%, g=0.28. Versión mejorada.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con selectividad extrema",
    "configuracion": "DGU",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro",
    "tl": 60,
    "shgc": 0.28,
    "sc": 0.33,
    "sel": 2.14,
    "u": "1.5 aire / 1.2 argon",
    "ref_ext": 14,
    "ref_int": 17,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "ES_DGU",
    "aplicaciones": "Edificios de oficinas; centros comerciales; residencias de lujo; hoteles; restaurantes; escuelas; hospitales",
    "beneficios": "Selectividad extrema mejorada (2.14); máximo control solar; alta luz natural; bajo U-value; 2da generación",
    "necesidad": "Fachada de alta gama con selectividad extrema mejorada sobre la primera versión",
    "pitch": "Versión mejorada del 60/28 con selectividad 2.14. Prácticamente el mismo desempeño pero con tecnología de recubrimiento de 2da generación.",
    "notas": "DGU, EN410. Selectividad 2.14 supera a la primera generación 60/28 (2.11). U argon=1.2.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-xtreme"
  },
  {
    "nombre": "COOL-LITE XTREME 50/22 II",
    "familia": "Cool-Lite Xtreme",
    "slug": "cool-lite-xtreme",
    "desc": "Selectividad extrema (2.09), máximo control solar. TL=46%, g=0.22.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con selectividad extrema",
    "configuracion": "DGU",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro",
    "tl": 46,
    "shgc": 0.22,
    "sc": 0.25,
    "sel": 2.09,
    "u": "1.5 aire / 1.2 argon",
    "ref_ext": 16,
    "ref_int": 18,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "ES_DGU",
    "aplicaciones": "Edificios de oficinas; centros comerciales; residencias de lujo; hoteles en climas extremos",
    "beneficios": "Máximo rechazo solar (g=0.22) de la gama Xtreme; alta selectividad (2.09); bajo U-value; para climas muy soleados",
    "necesidad": "Fachada en clima extremo que necesita el mayor bloqueo solar posible con aceptable luz natural",
    "pitch": "El Xtreme con mayor control solar (g=0.22). Para proyectos en zonas costeras o desérticas con exposición solar extrema. Bloquea más calor que cualquier otro Xtreme.",
    "notas": "DGU, EN410. g=0.22 es el más bajo de la serie Xtreme. U argon=1.2.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-xtreme"
  },
  {
    "nombre": "COOL-LITE XTREME 70/33",
    "familia": "Cool-Lite Xtreme",
    "slug": "cool-lite-xtreme",
    "desc": "Selectividad extrema (2.06), alta transmisión. TL=68%, g=0.33. Primera gen.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con selectividad extrema",
    "configuracion": "DGU",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro",
    "tl": 68,
    "shgc": 0.33,
    "sc": 0.38,
    "sel": 2.06,
    "u": "1.5 aire / 1.2 argon",
    "ref_ext": 11,
    "ref_int": 13,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "ES_DGU",
    "aplicaciones": "Edificios de oficinas; centros comerciales; residencias de lujo; hoteles; restaurantes",
    "beneficios": "TL muy alta (68%); selectividad extrema (2.06); aspecto muy transparente; bajo U-value; máxima luminosidad",
    "necesidad": "Fachada casi transparente que maximiza la luz natural con buen control solar y bajo U-value",
    "pitch": "La opción más luminosa de los Xtreme. TL=68% con selectividad 2.06: casi como un vidrio transparente pero con control solar premium.",
    "notas": "DGU, EN410. Mínima reflexión exterior (11%): aspecto muy limpio y transparente. U argon=1.2.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-xtreme"
  },
  {
    "nombre": "COOL-LITE XTREME 70/33 II",
    "familia": "Cool-Lite Xtreme",
    "slug": "cool-lite-xtreme",
    "desc": "Selectividad extrema gen.2 (2.06), alta transmisión. TL=68%, g=0.33.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con selectividad extrema",
    "configuracion": "DGU",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro",
    "tl": 68,
    "shgc": 0.33,
    "sc": 0.38,
    "sel": 2.06,
    "u": "1.5 aire / 1.2 argon",
    "ref_ext": 11,
    "ref_int": 13,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "ES_DGU",
    "aplicaciones": "Edificios de oficinas; centros comerciales; residencias de lujo; hoteles; restaurantes",
    "beneficios": "TL muy alta (68%); selectividad extrema (2.06); 2da generación; aspecto muy transparente; bajo U-value",
    "necesidad": "Fachada casi transparente con tecnología de 2da generación, control solar premium y máxima luminosidad",
    "pitch": "Segunda generación del 70/33, igual desempeño óptico pero con recubrimiento de tecnología más avanzada.",
    "notas": "DGU, EN410. Mismas especificaciones ópticas que 70/33 primera gen. U argon=1.2.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-xtreme"
  },
  {
    "nombre": "COOL-LITE XTREME 60/28 DIAMANT",
    "familia": "Cool-Lite Xtreme",
    "slug": "cool-lite-xtreme",
    "desc": "Selectividad extrema sobre base extra-clara (2.07). TL=60%, g=0.29. Sin tinte verde.",
    "segmento": "Comercial / Fachadas",
    "aplicacion_principal": "Fachadas premium con selectividad extrema y máxima neutralidad",
    "configuracion": "DGU",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro extra-claro",
    "tl": 60,
    "shgc": 0.29,
    "sc": 0.33,
    "sel": 2.07,
    "u": "1.5 aire / 1.2 argon",
    "ref_ext": 14,
    "ref_int": 17,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "ES_DGU",
    "aplicaciones": "Edificios de oficinas premium; residencias de lujo; fachadas con exigencia de máxima neutralidad de color",
    "beneficios": "Selectividad extrema (2.07); base Diamant extra-clara (sin tinte verde); máxima neutralidad de color; bajo U-value",
    "necesidad": "Fachada de alta gama donde se requiere máxima neutralidad cromática además de selectividad extrema",
    "pitch": "La versión DIAMANT usa vidrio base extra-claro (bajo hierro) eliminando el tinte verdoso. Para proyectos donde la pureza del color es tan importante como el desempeño energético.",
    "notas": "DGU, EN410. Fabricado sobre base SGG Diamant (extra-claro). Sin reflexión verdosa. U argon=1.2.",
    "url": "https://www.mx.saint-gobain-glass.com/products/cool-lite-xtreme"
  },
  {
    "nombre": "EVO 50",
    "familia": "EVO",
    "slug": "sgg-evo",
    "desc": "Control solar residencial. TL=51%, g=0.55. Bloquea 43% del calor vs claro.",
    "segmento": "Residencial",
    "aplicacion_principal": "Ventanas y fachadas residenciales",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Neutro",
    "tl": 51,
    "shgc": 0.55,
    "sc": 0.63,
    "sel": 0.93,
    "u": "5.6",
    "ref_ext": 18,
    "ref_int": 17,
    "norma": "EN673",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Aplicaciones residenciales y comerciales; ventanas; puertas; mamparas",
    "beneficios": "Bloquea 43% del calor vs vidrio claro; buena luz natural (51%); protección UV; ahorro en AC",
    "necesidad": "Hogar o local comercial que quiere reducir el calor sin oscurecer el espacio",
    "pitch": "EVO 50: el punto de entrada perfecto para eficiencia energética residencial. Bloquea casi la mitad del calor manteniendo una excelente luminosidad.",
    "notas": "Monolítico 6mm, EN673. U mono=5.6 W/m²K (sin DGU). Para mejor U-value combinar con EVO DUO.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sgg-evo"
  },
  {
    "nombre": "EVO 67",
    "familia": "EVO",
    "slug": "sgg-evo",
    "desc": "Control solar suave, casi transparente. TL=67%, g=0.67. Bloquea 31% del calor.",
    "segmento": "Residencial",
    "aplicacion_principal": "Ventanas y fachadas residenciales",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Neutro",
    "tl": 67,
    "shgc": 0.67,
    "sc": 0.77,
    "sel": 0.99,
    "u": "5.6",
    "ref_ext": 19,
    "ref_int": 19,
    "norma": "EN673",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Aplicaciones residenciales y comerciales; ventanas; puertas con marcos; fachadas ligeras",
    "beneficios": "Alta transmisión de luz (67%); aspecto casi transparente; protección UV; algo de control solar",
    "necesidad": "Reemplazar vidrio claro convencional con algo de protección solar sin perder la sensación de transparencia",
    "pitch": "EVO 67: para quien quiere la experiencia del vidrio claro pero con protección solar básica y protección UV. El upgrade mínimo desde vidrio claro convencional.",
    "notas": "Monolítico 6mm, EN673. Casi idéntico al vidrio claro visualmente. U mono=5.6 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sgg-evo"
  },
  {
    "nombre": "EVO Blue",
    "familia": "EVO",
    "slug": "sgg-evo",
    "desc": "Control solar intenso con tono azul. Factor Solar g≈0.38. Bloquea ~62% del calor.",
    "segmento": "Residencial",
    "aplicacion_principal": "Ventanas y fachadas residenciales",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Azul",
    "tl": null,
    "shgc": 0.38,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "EN673",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Aplicaciones residenciales; ventanas; puertas; fachadas ligeras con diseño",
    "beneficios": "Alto control solar; estética azul distintiva; protección UV; bloquea 62% del calor",
    "necesidad": "Ventanas o fachadas donde se quiere máxima protección solar con un tono azul moderno",
    "pitch": "EVO Blue es la opción de mayor bloqueo solar de la gama monolítica EVO con un diseño azul contemporáneo. Para casas y locales con estética moderna.",
    "notas": "Datos de infográfico de marketing. TL% no publicado en tabla técnica del sitio. Factor solar g≈0.38.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sgg-evo"
  },
  {
    "nombre": "EVO Duo",
    "familia": "EVO",
    "slug": "sgg-evo",
    "desc": "DGU residencial low-E. TL=70%, g=0.57, U_aire=1.8. Aislamiento térmico + acústico.",
    "segmento": "Residencial",
    "aplicacion_principal": "Ventanas residenciales con aislamiento premium",
    "configuracion": "DGU (4+12Aire+6mm)",
    "espesor_mm": "4+6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Neutro",
    "tl": 70,
    "shgc": 0.57,
    "sc": 0.63,
    "sel": 1.22,
    "u": "1.8 aire / 1.5 argon",
    "ref_ext": 13,
    "ref_int": 12,
    "norma": "EN673",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Aplicaciones residenciales con aislamiento térmico y acústico; ventanas; puertas; mamparas",
    "beneficios": "Aislamiento térmico (U=1.8); aislamiento acústico; buena luz natural (70%); control solar moderado; protección UV",
    "necesidad": "Hogar que necesita aislamiento térmico y acústico además de control solar básico",
    "pitch": "EVO Duo: el DGU residencial completo. Combina control solar, aislamiento térmico (U=1.8) y reducción de ruido exterior en un solo producto.",
    "notas": "DGU 4mm+12Aire+6mm, EN673. U argon=1.5 W/m²K. Aislamiento acústico incluido.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sgg-evo"
  },
  {
    "nombre": "EVO Duo Max",
    "familia": "EVO",
    "slug": "sgg-evo",
    "desc": "DGU residencial alta selectividad. TL=69%, g=0.34, U_aire=1.6. Máxima eficiencia.",
    "segmento": "Residencial",
    "aplicacion_principal": "Ventanas residenciales con eficiencia energética máxima",
    "configuracion": "DGU",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3300x6100 / 3300x2600",
    "color": "Neutro",
    "tl": 69,
    "shgc": 0.34,
    "sc": 0.39,
    "sel": 2.03,
    "u": "1.6 aire / 1.5 argon",
    "ref_ext": 13,
    "ref_int": 15,
    "norma": "EN673",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "ES_DGU",
    "aplicaciones": "Aplicaciones residenciales premium con máxima eficiencia energética; ventanas; puertas; mamparas",
    "beneficios": "Selectividad extrema (2.03); bajo U-value (1.6); alta luz natural (69%); bloquea 66% del calor; aislamiento acústico",
    "necesidad": "Hogar que quiere el máximo desempeño energético posible en DGU residencial",
    "pitch": "EVO Duo Max: el mejor de la gama EVO. Selectividad 2.03 comparable a los Xtreme comerciales, en un producto pensado para residencias. U=1.6 y TL=69% es una combinación excepcional.",
    "notas": "DGU, EN673. Selectividad 2.03: referencia en el mercado residencial. U argon=1.5. Aislamiento acústico incluido.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sgg-evo"
  },
  {
    "nombre": "PARSOL Gris",
    "familia": "Parsol",
    "slug": "parsol",
    "desc": "Vidrio tintado gris. TL=43%, g=0.57. Control solar básico, espesores 2-12mm.",
    "segmento": "Residencial / Comercial / Fachadas",
    "aplicacion_principal": "Ventanas, fachadas básicas y acristalamientos en general",
    "configuracion": "Monolítico",
    "espesor_mm": "6 (ref; 2-12mm)",
    "dimensiones_max_mm": "6000x3210",
    "color": "Gris",
    "tl": 43,
    "shgc": 0.57,
    "sc": 0.66,
    "sel": 0.75,
    "u": "5.7",
    "ref_ext": 5,
    "ref_int": 5,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Acristalamiento universal; fachadas básicas; ventanas residenciales; interiores decorativos; base para vidrio a capas; espejos; laminados",
    "beneficios": "Control solar básico; tono gris elegante; reduce calor solar; base procesable para múltiples aplicaciones",
    "necesidad": "Vidrio económico con control solar básico y estética gris para aplicaciones en fachadas o ventanas sin requisitos de alto desempeño",
    "pitch": "PARSOL Gris: el vidrio de control solar más accesible. Tono gris clásico que reduce el calor básicamente y sirve de base para capas de alto desempeño.",
    "notas": "EN410, monolítico. Specs referencia 6mm. Disponible en 2-12mm (varía por color). Puede servir de base para Cool-Lite ST, KNT, etc.",
    "url": "https://www.mx.saint-gobain-glass.com/products/parsol"
  },
  {
    "nombre": "PARSOL Verde",
    "familia": "Parsol",
    "slug": "parsol",
    "desc": "Vidrio tintado verde. TL=73%, g=0.55. Alta transmisión con tono verde, espesores 3-12mm.",
    "segmento": "Residencial / Comercial / Fachadas",
    "aplicacion_principal": "Ventanas, fachadas básicas y acristalamientos en general",
    "configuracion": "Monolítico",
    "espesor_mm": "6 (ref; 3-12mm)",
    "dimensiones_max_mm": "6000x3210",
    "color": "Verde",
    "tl": 73,
    "shgc": 0.55,
    "sc": 0.64,
    "sel": 1.33,
    "u": "5.7",
    "ref_ext": 7,
    "ref_int": 7,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Acristalamiento universal; fachadas; ventanas residenciales; interiores decorativos; base para vidrio a capas",
    "beneficios": "Alta transmisión de luz (73%); tono verde natural; selectividad >1; control solar básico",
    "necesidad": "Vidrio económico con alta luz natural y tono verde para ventanas y fachadas sin requisitos premium",
    "pitch": "PARSOL Verde: el más luminoso de la familia Parsol con selectividad sorprendentemente alta (1.33). Para casas que quieren tono verde con mucha luz.",
    "notas": "EN410, monolítico. Specs referencia 6mm. Disponible en 3-12mm. Selectividad 1.33 destaca en vidrios tintados básicos.",
    "url": "https://www.mx.saint-gobain-glass.com/products/parsol"
  },
  {
    "nombre": "PARSOL Bronce",
    "familia": "Parsol",
    "slug": "parsol",
    "desc": "Vidrio tintado bronce/ámbar. TL=49%, g=0.60. Estética cálida, espesores 4-6mm.",
    "segmento": "Residencial / Comercial / Fachadas",
    "aplicacion_principal": "Ventanas, fachadas básicas y acristalamientos en general",
    "configuracion": "Monolítico",
    "espesor_mm": "6 (ref; 4-6mm)",
    "dimensiones_max_mm": "6000x3210",
    "color": "Bronce",
    "tl": 49,
    "shgc": 0.6,
    "sc": 0.69,
    "sel": 0.82,
    "u": "5.7",
    "ref_ext": 5,
    "ref_int": 5,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Acristalamiento universal; fachadas; ventanas; interiores cálidos; edificios clásicos",
    "beneficios": "Tono bronce/dorado cálido; buena transmisión de luz; control solar básico; estética atemporal",
    "necesidad": "Fachada o ventana con estética cálida y algo de control solar sin inversión en vidrio de alto desempeño",
    "pitch": "PARSOL Bronce: para proyectos con estética clásica o cálida. El tono bronce/ámbar da calidez al espacio manteniendo buena iluminación.",
    "notas": "EN410, monolítico. Specs referencia 6mm. Disponible en 4-6mm únicamente.",
    "url": "https://www.mx.saint-gobain-glass.com/products/parsol"
  },
  {
    "nombre": "PARSOL Gris+",
    "familia": "Parsol",
    "slug": "parsol",
    "desc": "Vidrio tintado gris intenso (mayor control solar que Gris). Specs no publicadas en web.",
    "segmento": "Residencial / Comercial / Fachadas",
    "aplicacion_principal": "Ventanas, fachadas básicas y acristalamientos en general",
    "configuracion": "Monolítico",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Gris intenso",
    "tl": null,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Acristalamiento universal; fachadas; ventanas residenciales",
    "beneficios": "Mayor control solar que Parsol Gris estándar; tono gris más intenso",
    "necesidad": "Vidrio tintado gris con mayor densidad que el Parsol Gris para más control solar",
    "pitch": "PARSOL Gris+: cuando el Parsol Gris estándar no es suficiente. Mayor densidad de tinte para mayor bloqueo solar.",
    "notas": "Especificaciones técnicas no publicadas en el sitio web del fabricante. Consultar a SG Glass México.",
    "url": "https://www.mx.saint-gobain-glass.com/products/parsol"
  },
  {
    "nombre": "PARSOL Verde+",
    "familia": "Parsol",
    "slug": "parsol",
    "desc": "Vidrio tintado verde intenso (mayor control solar que Verde). Specs no publicadas en web.",
    "segmento": "Residencial / Comercial / Fachadas",
    "aplicacion_principal": "Ventanas, fachadas básicas y acristalamientos en general",
    "configuracion": "Monolítico",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Verde intenso",
    "tl": null,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Acristalamiento universal; fachadas; ventanas residenciales",
    "beneficios": "Mayor control solar que Parsol Verde estándar; tono verde más intenso",
    "necesidad": "Vidrio tintado verde con mayor densidad para más control solar",
    "pitch": "PARSOL Verde+: la versión de mayor densidad del tinte verde con mejor control solar que el Verde estándar.",
    "notas": "Especificaciones técnicas no publicadas en el sitio web del fabricante. Consultar a SG Glass México.",
    "url": "https://www.mx.saint-gobain-glass.com/products/parsol"
  },
  {
    "nombre": "SOL-LITE Claro",
    "familia": "Sol-Lite",
    "slug": "sol-lite",
    "desc": "Control solar reflectivo claro. TL=32%, g=0.51. Alta reflexión 46%. Privacidad diurna.",
    "segmento": "Residencial / Comercial",
    "aplicacion_principal": "Ventanas y fachadas residenciales y comerciales",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Claro (reflectivo)",
    "tl": 32,
    "shgc": 0.51,
    "sc": 0.58,
    "sel": 0.63,
    "u": "5.7",
    "ref_ext": 46,
    "ref_int": 54,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "SI",
    "aplicaciones": "Viviendas; escuelas; hoteles; edificios residenciales",
    "beneficios": "Alta reflexión exterior (46%); privacidad diurna; control solar moderado; protección UV 92-97%",
    "necesidad": "Ventana residencial que necesita privacidad durante el día y control de calor básico sin oscurecer demasiado el interior",
    "pitch": "SOL-LITE Claro: el balance entre privacidad y luz. Alta reflexión exterior (46%) da privacidad durante el día. Muy popular en casas de zonas residenciales.",
    "notas": "EN410, monolítico 6mm. Efecto espejo: se ve hacia afuera durante el día, privacidad hacia adentro. U=5.7 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sol-lite"
  },
  {
    "nombre": "SOL-LITE Verde",
    "familia": "Sol-Lite",
    "slug": "sol-lite",
    "desc": "Control solar reflectivo verde. TL=26%, g=0.35. Alta privacidad, tono verde.",
    "segmento": "Residencial / Comercial",
    "aplicacion_principal": "Ventanas y fachadas residenciales y comerciales",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Verde (reflectivo)",
    "tl": 26,
    "shgc": 0.35,
    "sc": 0.4,
    "sel": 0.74,
    "u": "5.7",
    "ref_ext": 32,
    "ref_int": 53,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "SI",
    "aplicaciones": "Viviendas; escuelas; hoteles; edificios residenciales",
    "beneficios": "Buen control solar (g=0.35); tono verde moderno; privacidad diurna; protección UV 92-97%",
    "necesidad": "Ventana con control solar mejorado y estética verde con privacidad",
    "pitch": "SOL-LITE Verde: mayor control solar que el Claro con estética verde contemporánea. Para casas que quieren privacidad con tono verde.",
    "notas": "EN410, monolítico 6mm. Reflectividad interior alta (53%). U=5.7 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sol-lite"
  },
  {
    "nombre": "SOL-LITE Gris",
    "familia": "Sol-Lite",
    "slug": "sol-lite",
    "desc": "Control solar reflectivo gris. TL=15%, g=0.41. Máxima privacidad, tono gris.",
    "segmento": "Residencial / Comercial",
    "aplicacion_principal": "Ventanas y fachadas residenciales y comerciales",
    "configuracion": "Monolítico",
    "espesor_mm": "6",
    "dimensiones_max_mm": "N/D",
    "color": "Gris (reflectivo)",
    "tl": 15,
    "shgc": 0.41,
    "sc": 0.47,
    "sel": 0.37,
    "u": "5.7",
    "ref_ext": 14,
    "ref_int": 53,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "SI",
    "aplicaciones": "Viviendas; escuelas; hoteles; edificios residenciales",
    "beneficios": "Máxima privacidad (TL=15%); tono gris intenso; reflectividad interior alta (53%); protección UV",
    "necesidad": "Ventana de máxima privacidad con mínima transmisión de luz y tono gris",
    "pitch": "SOL-LITE Gris: para quien quiere máxima privacidad durante el día. Con solo 15% de transmisión de luz, se convierte prácticamente en una pared visible desde afuera.",
    "notas": "EN410, monolítico 6mm. TL=15%: el más oscuro de Sol-Lite. Selectividad 0.37 baja. U=5.7 W/m²K.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sol-lite"
  },
  {
    "nombre": "STADIP",
    "familia": "Stadip",
    "slug": "stadip",
    "desc": "Laminado seguridad estándar. 1 PVB 0.38mm. Clase EN12600: 2B2. Espesores 4-12mm.",
    "segmento": "Residencial / Comercial / Industrial",
    "aplicacion_principal": "Acristalamientos de seguridad interiores y exteriores",
    "configuracion": "Laminado (PVB)",
    "espesor_mm": "4-12 (laminado)",
    "dimensiones_max_mm": "N/D",
    "color": "Según vidrio base",
    "tl": "Según base",
    "shgc": "Según base",
    "sc": "Según base",
    "sel": "Según base",
    "u": "Según base",
    "ref_ext": "Según base",
    "ref_int": "Según base",
    "norma": "EN12600",
    "templable": "SI (post-laminado)",
    "laminable": "ES_LAMINADO",
    "dgu": "SI",
    "aplicaciones": "Terrazas; domos; tragaluces; barandales; particiones; acristalamiento inclinado; vitrinas; ventanas",
    "beneficios": "Seguridad ante rotura (fragmentos adheridos al PVB); filtración UV 99%; versatilidad de procesamiento",
    "necesidad": "Acristalamiento que debe mantenerse íntegro ante impacto para proteger a las personas",
    "pitch": "STADIP: la solución de seguridad más económica. En caso de rotura los fragmentos quedan adheridos al PVB. Cumple EN12600 2B2. Para terrazas, domos y cualquier acristalamiento en área de tránsito.",
    "notas": "Composición: vidrio+PVB 0.38mm+vidrio. Nomenclatura: ej. STADIP 33.1=3mm+3mm. Espesores disponibles: 4,6,8,10,12mm.",
    "url": "https://www.mx.saint-gobain-glass.com/products/stadip"
  },
  {
    "nombre": "STADIP PROTECT",
    "familia": "Stadip",
    "slug": "stadip",
    "desc": "Laminado seguridad alta. 2+ PVBs. Clase EN12600: 1B1. Espesores 7-13mm.",
    "segmento": "Residencial / Comercial / Industrial",
    "aplicacion_principal": "Acristalamientos de alta seguridad",
    "configuracion": "Laminado (PVB múltiple)",
    "espesor_mm": "7-13 (laminado)",
    "dimensiones_max_mm": "N/D",
    "color": "Según vidrio base",
    "tl": "Según base",
    "shgc": "Según base",
    "sc": "Según base",
    "sel": "Según base",
    "u": "Según base",
    "ref_ext": "Según base",
    "ref_int": "Según base",
    "norma": "EN12600",
    "templable": "SI (post-laminado)",
    "laminable": "ES_LAMINADO",
    "dgu": "SI",
    "aplicaciones": "Barandales; tragaluces; acristalamiento inclinado expuesto; zonas de alto riesgo de impacto humano",
    "beneficios": "Alta seguridad (clase 1B1); protección contra caída de personas; múltiples capas PVB; filtración UV 99%",
    "necesidad": "Acristalamiento en zonas donde hay riesgo de caída o impacto de personas (barandales, escaleras, balcones)",
    "pitch": "STADIP PROTECT: cuando la seguridad es crítica. Clase 1B1 significa resistencia probada al impacto de personas. Obligatorio en muchos códigos de construcción para barandales y tragaluces.",
    "notas": "Composición: 2+ PVBs 0.38mm o 1 PVB 0.76mm. Ej. STADIP 44.2=4mm+4mm. Espesores: 7,9,11,13mm. Cumple EN12600 1B1.",
    "url": "https://www.mx.saint-gobain-glass.com/products/stadip"
  },
  {
    "nombre": "STADIP SILENCE",
    "familia": "Stadip",
    "slug": "stadip",
    "desc": "Laminado acústico. PVB especial acústico. Mejor STC que STADIP convencional.",
    "segmento": "Residencial / Comercial",
    "aplicacion_principal": "Acristalamientos con alto aislamiento acústico",
    "configuracion": "Laminado (PVB acústico)",
    "espesor_mm": "Igual a STADIP",
    "dimensiones_max_mm": "N/D",
    "color": "Según vidrio base",
    "tl": "Según base",
    "shgc": "Según base",
    "sc": "Según base",
    "sel": "Según base",
    "u": "Según base",
    "ref_ext": "Según base",
    "ref_int": "Según base",
    "norma": "EN12600",
    "templable": "SI (post-laminado)",
    "laminable": "ES_LAMINADO",
    "dgu": "SI",
    "aplicaciones": "Ventanas en zonas de alto ruido; hoteles frente a avenidas; aeropuertos; estudios de grabación; edificios junto a vías del tren",
    "beneficios": "Mayor aislamiento acústico que STADIP convencional; misma seguridad; filtración UV 99%; confort acústico mejorado",
    "necesidad": "Ventanas cerca de fuentes de ruido intenso donde el vidrio laminado estándar no logra el aislamiento deseado",
    "pitch": "STADIP SILENCE: cuando el ruido es el enemigo. La capa viscoelástica de PVB acústico atenúa las frecuencias molestas. Mismo aspecto que vidrio normal, mejor silencio interior.",
    "notas": "PVB acústico especial en lugar de PVB estándar. Mismo perfil de seguridad que STADIP. Consultar especificaciones de STC con SG México.",
    "url": "https://www.mx.saint-gobain-glass.com/products/stadip"
  },
  {
    "nombre": "SGG Planilux",
    "familia": "Flotado / Base",
    "slug": "sgg-planilux",
    "desc": "Vidrio flotado claro de alta calidad. La base de todos los procesos de transformación.",
    "segmento": "Residencial / Comercial / Industrial / Decorativo",
    "aplicacion_principal": "Acristalamientos en general y vidrio base",
    "configuracion": "Monolítico",
    "espesor_mm": "2-19",
    "dimensiones_max_mm": "6000x3210 (estándar)",
    "color": "Incoloro / Claro",
    "tl": 89,
    "shgc": 0.87,
    "sc": 1,
    "sel": 1.02,
    "u": "5.8",
    "ref_ext": 8,
    "ref_int": 8,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Fachadas de edificios; muebles; decoración de interiores; uso residencial; base para vidrio espejo; vidrio templado; vidrio laminado; DGU",
    "beneficios": "Versatilidad total de procesamiento; alta transparencia; calidad óptica perfecta; compatible con todas las transformaciones",
    "necesidad": "Base de vidrio para cualquier aplicación donde se requiera un vidrio claro de calidad sin funcionalidad especial",
    "pitch": "SGG Planilux: el vidrio de referencia. Todo comienza aquí. Sin él no existen los espejos, templados, laminados ni vidrios a capas de Saint-Gobain.",
    "notas": "Gama completa: 2,3,4,5,6,8,10,12,15,19mm. Specs ópticas son para 6mm (típico).",
    "url": "https://www.mx.saint-gobain-glass.com/products/sgg-planilux"
  },
  {
    "nombre": "SGG Diamant",
    "familia": "Flotado / Base",
    "slug": "diamant",
    "desc": "Vidrio extra-claro de máxima transparencia. Sin tinte verdoso. TL≈91%.",
    "segmento": "Residencial / Comercial / Decorativo / Arquitectónico",
    "aplicacion_principal": "Interiores de alta gama, vitrinas, fachadas premium",
    "configuracion": "Monolítico",
    "espesor_mm": "3-19",
    "dimensiones_max_mm": "6000x3210",
    "color": "Extra-claro (incoloro neutro)",
    "tl": 91,
    "shgc": 0.9,
    "sc": 1.03,
    "sel": 1.01,
    "u": "5.7",
    "ref_ext": 8,
    "ref_int": 8,
    "norma": "EN410",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Decoración; separadores de ambientes; puertas; mamparas de ducha; estanterías; mostradores; vitrinas; joyerías; museos; galerías; fachadas; muros cortina",
    "beneficios": "Máxima transparencia; sin tinte verdoso; colores naturales perfectos; calidad óptica excepcional; compatible con capas antirreflejo",
    "necesidad": "Aplicaciones donde la neutralidad cromática y la máxima transparencia son esenciales: vitrinas de lujo, obras de arte, fachadas premium",
    "pitch": "SGG Diamant: cuando importa ver los colores reales. Sin el tinte verde del flotado convencional. Para joyerías, museos, galerías y fachadas de alta gama.",
    "notas": "Bajo contenido de hierro (<0.01% vs 0.1% del Planilux). Disponible en 3,4,5,6,8,10,12,15,19mm. Base para COOL-LITE XTREME 60/28 DIAMANT.",
    "url": "https://www.mx.saint-gobain-glass.com/products/diamant"
  },
  {
    "nombre": "Bioclean",
    "familia": "Funcional / Bajo Mantenimiento",
    "slug": "sgg-bioclean",
    "desc": "Vidrio auto-limpiante con capa fotocatalítica e hidrofílica. Menos limpieza.",
    "segmento": "Residencial / Comercial",
    "aplicacion_principal": "Ventanas y fachadas exteriores de difícil acceso",
    "configuracion": "Monolítico / DGU / Laminado",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro (transparente)",
    "tl": 89,
    "shgc": 0.87,
    "sc": 1,
    "sel": 1.02,
    "u": "5.8",
    "ref_ext": 8,
    "ref_int": 8,
    "norma": "N/D",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Ventanas; domos; ventanales; fachadas; balcones; barandales",
    "beneficios": "Menor frecuencia de limpieza; capa hidrofílica (lluvia arrastra suciedad); fotocatálisis con UV solar; sin manchas de agua; visión más clara en lluvia; ecológico",
    "necesidad": "Edificio o residencia con ventanas o fachadas de difícil acceso o en zona contaminada",
    "pitch": "Bioclean: la solución para ventanas que siempre están sucias. La capa hace que el sol descomponga la suciedad y la lluvia la limpie. Para edificios altos, domos y zonas industriales.",
    "notas": "Capa de TiO2 en cara exterior. No modifica apariencia vs Planilux. Specs ópticas ≈ Planilux. 100% reciclable, 30% material reciclado.",
    "url": "https://www.mx.saint-gobain-glass.com/products/sgg-bioclean"
  },
  {
    "nombre": "Crystal Gold",
    "familia": "Industrial / Electrodoméstico",
    "slug": "crystal-gold",
    "desc": "Vidrio a capas para puertas de horno. Capa metálica cara #1. Solo 4mm.",
    "segmento": "Industrial / Electrodoméstico",
    "aplicacion_principal": "Puertas de horno para estufas (OEM)",
    "configuracion": "Monolítico / Laminable",
    "espesor_mm": "4",
    "dimensiones_max_mm": "N/D (contactar SG)",
    "color": "Metálico dorado",
    "tl": null,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "N/D",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Vidrio exterior en puertas de hornos para estufas; OEM electrodomésticos",
    "beneficios": "Estética metálica dorada; resistencia al calor; serigrafiable; curvarable; laminable; sin decapado necesario",
    "necesidad": "Fabricante de estufas que necesita vidrio exterior de puerta de horno con estética premium",
    "pitch": "Crystal Gold: específicamente desarrollado para OEM de electrodomésticos. La capa metálica da una estética de alta gama a las puertas de horno.",
    "notas": "Disponible en 4mm únicamente. Capa en cara 1 (exterior). Para uso industrial/OEM. Dimensiones según requerimiento.",
    "url": "https://www.mx.saint-gobain-glass.com/products/crystal-gold"
  },
  {
    "nombre": "Eko Energy",
    "familia": "Industrial / Refrigeración",
    "slug": "eko-energy",
    "desc": "Vidrio calefactable (TCO) para refrigeradores comerciales. Anti-condensación.",
    "segmento": "Industrial / Comercial / Refrigeración",
    "aplicacion_principal": "Puertas de refrigerador y congelador vertical",
    "configuracion": "DGU / TGU",
    "espesor_mm": "3.15 / 4",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro (alta transparencia)",
    "tl": "Alta",
    "shgc": "Alta",
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": "Baja",
    "ref_int": "Baja",
    "norma": "N/D",
    "templable": "SI (requerido)",
    "laminable": "NO",
    "dgu": "ES_DGU",
    "aplicaciones": "Refrigeradores verticales; congeladores verticales; vitrinas refrigeradas; sistemas retrofit",
    "beneficios": "Anti-condensación; alta visibilidad de productos; bajo mantenimiento; compatible con Planitherm ONE; bajo consumo energético",
    "necesidad": "Supermercado o tienda que necesita puertas de refrigerador sin condensación para mejor visibilidad de productos",
    "pitch": "Eko Energy: elimina el problema de la puerta empañada del refrigerador. Con calefacción eléctrica (TCO) en el vidrio, la condensación nunca aparece. Más ventas al ser siempre visibles los productos.",
    "notas": "Vidrio TCO (Óxido Conductor Transparente) + calefacción eléctrica via busbars. Requiere templado. 3.15mm y 4mm. Compatible con Planitherm ONE para máxima eficiencia.",
    "url": "https://www.mx.saint-gobain-glass.com/products/eko-energy"
  },
  {
    "nombre": "Eko Vision+",
    "familia": "Industrial / Electrodoméstico",
    "slug": "eko-vision",
    "desc": "Vidrio low-E para puertas de horno de cocina. Anti-condensación, alta seguridad.",
    "segmento": "Industrial / Electrodoméstico",
    "aplicacion_principal": "Paneles de vidrio aislante en puertas de horno",
    "configuracion": "Monolítico (base para IGU)",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro (tono azul suave)",
    "tl": "Alta",
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": "Baja",
    "ref_int": null,
    "norma": "ANSI Z21.1",
    "templable": "SI (requerido)",
    "laminable": "NO",
    "dgu": "SI",
    "aplicaciones": "Puertas de hornos de cocina; estufas premium; OEM electrodomésticos",
    "beneficios": "Alta seguridad (vidrio frontal más frío); cumple ANSI Z21.1 <78°C; fácil limpieza; alta visión interior; tono azul elegante; no se empaña",
    "necesidad": "Fabricante de hornos de cocina que necesita vidrio de alta seguridad y bajo consumo energético",
    "pitch": "Eko Vision+: el upgrade para fabricantes de hornos. El vidrio frontal se mantiene frío al tacto (cumple <78°C) protegiendo a niños y mascotas. Tono azul premium.",
    "notas": "Vidrio low-E magnetrónico, requiere templado obligatorio. Tono azul en reflexión. ANSI Z21.1 certificado.",
    "url": "https://www.mx.saint-gobain-glass.com/products/eko-vision"
  },
  {
    "nombre": "Miralite Revolution",
    "familia": "Espejos",
    "slug": "miralite-revolution",
    "desc": "Espejo ecológico sin cobre ni plomo. Alta durabilidad. Colores: Plata/Bronce/Gris/Verde.",
    "segmento": "Residencial / Comercial / Decorativo",
    "aplicacion_principal": "Espejos interiores y decorativos",
    "configuracion": "Espejo",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Plata / Bronce / Gris / Verde",
    "tl": null,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "N/D",
    "templable": "NO",
    "laminable": "NO",
    "dgu": "NO",
    "aplicaciones": "Lobbies; ascensores; baños; pasillos; bares; restaurantes; hoteles; gimnasios; centros comerciales; mobiliario",
    "beneficios": "Sin sustancias tóxicas (cobre y plomo); ecológico; alta durabilidad; amplia gama de colores; bienestar y salud",
    "necesidad": "Espejo de interiores donde la responsabilidad ambiental y la durabilidad son importantes",
    "pitch": "Miralite Revolution: el espejo del futuro, hoy. Sin plomo ni cobre. Para proyectos con certificación LEED o política de materiales verdes. Disponible en colores para diseños únicos.",
    "notas": "Sin cobre ni plomo: más seguro en instalación y disposición. Colores: Plata (estándar), Bronce, Gris, Verde. Para uso interior.",
    "url": "https://www.mx.saint-gobain-glass.com/products/miralite-revolution"
  },
  {
    "nombre": "Miralite Black",
    "familia": "Espejos",
    "slug": "miralite-black",
    "desc": "Espejo negro con acabado de alto brillo. Resistente a UV, humedad y corrosión.",
    "segmento": "Residencial / Comercial / Decorativo",
    "aplicacion_principal": "Recubrimientos decorativos de interiores",
    "configuracion": "Espejo decorativo",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Negro brillante",
    "tl": null,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "N/D",
    "templable": "NO",
    "laminable": "NO",
    "dgu": "NO",
    "aplicaciones": "Revestimiento de interiores; mobiliario; espacios sanitarios; oficinas; cocinas; salas de juntas; lobbies; áreas comerciales",
    "beneficios": "Acabado negro brillante elegante; resistente a corrosión; resistente a UV; resistente a humedad; amplitud visual",
    "necesidad": "Interior que requiere acabado negro de alto brillo con propiedades de espejo para una estética sofisticada",
    "pitch": "Miralite Black: el espejo negro más elegante del mercado. Para interiorismo de alto nivel donde el negro mate no es suficiente. Efecto espejo en negro da profundidad y sofisticación.",
    "notas": "Uso exclusivo en interiores. No recomendado para exterior ni zonas con humedad excesiva sin protección. Alta resistencia UV.",
    "url": "https://www.mx.saint-gobain-glass.com/products/miralite-black"
  },
  {
    "nombre": "Miralite Illuminia",
    "familia": "Espejos",
    "slug": "miralite-illuminia",
    "desc": "Espejo sin plomo ni cobre, optimizado para aplicaciones con luz LED.",
    "segmento": "Residencial / Comercial / Decorativo",
    "aplicacion_principal": "Espejos retroiluminados y con integración LED",
    "configuracion": "Espejo",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Plata",
    "tl": null,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "N/D",
    "templable": "NO",
    "laminable": "NO",
    "dgu": "NO",
    "aplicaciones": "Espejos retroiluminados; baños con iluminación LED; salones de belleza; hoteles premium; espectáculos; centros comerciales",
    "beneficios": "Optimizado para retroiluminación LED; sin plomo ni cobre; alta durabilidad; ideal para espejos inteligentes",
    "necesidad": "Instalación de espejo retroiluminado con LED donde la transmisión de luz del backing es importante",
    "pitch": "Miralite Illuminia: diseñado para la era del espejo inteligente. El backing permite mayor paso de luz LED desde atrás. Para espejos de hotel, salones y proyectos de smart home.",
    "notas": "Sin cobre ni plomo como Miralite Revolution, pero con propiedades especiales para backlit LED. Para uso interior.",
    "url": "https://www.mx.saint-gobain-glass.com/products/miralite-illuminia"
  },
  {
    "nombre": "Mirastar",
    "familia": "Espejos",
    "slug": "mirastar",
    "desc": "Vidrio espejo de capa magnetrónica. Actúa como espejo real. Interior y exterior. 6mm.",
    "segmento": "Residencial / Comercial / Decorativo / Fachadas",
    "aplicacion_principal": "Espejos en interiores, fachadas y cabinas de ducha",
    "configuracion": "Vidrio espejo a capas",
    "espesor_mm": "6",
    "dimensiones_max_mm": "3210x2250",
    "color": "Cromo / Espejo",
    "tl": null,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "N/D",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "NO",
    "aplicaciones": "Mamparas de ducha; puertas; mobiliario; frentes de cocina; centros comerciales; fachadas; espejos unidireccionales",
    "beneficios": "Efecto espejo real con capa metálica; templable; serigrafiable; alta durabilidad en humedad; espejo unidireccional; seguridad al templar",
    "necesidad": "Espacio interior o exterior que requiere efecto espejo duradero en condiciones de humedad o uso intensivo",
    "pitch": "Mirastar: el espejo más versátil de Saint-Gobain. A diferencia de los espejos convencionales, se templa para mayor seguridad. Ideal para cabinas de ducha y espacios de alto tráfico.",
    "notas": "Capa magnetrónica de cromo. Espesor estándar: 6mm. Dimensión estándar: 3.21x2.25m. Templable: SI (seguridad). Para uso interior y algunas aplicaciones exteriores.",
    "url": "https://www.mx.saint-gobain-glass.com/products/mirastar"
  },
  {
    "nombre": "Planitherm ONE",
    "familia": "Low-E / Refrigeración",
    "slug": "planitherm-one",
    "desc": "Vidrio low-E para DGU/TGU en refrigeración comercial. Mayor eficiencia vs Low-E conv.",
    "segmento": "Industrial / Comercial / Refrigeración",
    "aplicacion_principal": "Refrigeradores verticales y congeladores",
    "configuracion": "Monolítico (para DGU/TGU)",
    "espesor_mm": "3-6",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro (transparente)",
    "tl": "Alta",
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": "Baja",
    "ref_int": null,
    "norma": "EN1096",
    "templable": "SI (versión ONE II)",
    "laminable": "NO",
    "dgu": "ES_COMPONENTE_DGU",
    "aplicaciones": "Refrigeradores verticales; vitrinas refrigeradas; sistemas retrofit; congeladores verticales; refrigeradores de vino",
    "beneficios": "Máximo aislamiento térmico para DGU; 20% mayor ahorro energético vs Low-E convencional; anti-condensación; color neutro; alta transparencia; bajo mantenimiento",
    "necesidad": "Fabricante o distribuidor de refrigeración comercial que necesita el máximo aislamiento con la mejor visibilidad del producto",
    "pitch": "Planitherm ONE: el low-E de referencia para refrigeración. Reduce la factura de electricidad del supermercado hasta un 20% sobre low-E convencional. La visibilidad perfecta aumenta las ventas.",
    "notas": "Capa en cara 2 o 3 del DGU/TGU. Espesores: 3mm-6mm. Versión templable: Planitherm ONE II. Amigable con el ambiente.",
    "url": "https://www.mx.saint-gobain-glass.com/products/planitherm-one"
  },
  {
    "nombre": "Planitherm UN II",
    "familia": "Low-E / Refrigeración",
    "slug": "planitherm-un-ii",
    "desc": "Vidrio low-E templable para refrigeración industrial. 17% ahorro vs Low-E convencional.",
    "segmento": "Industrial / Comercial / Refrigeración",
    "aplicacion_principal": "Refrigeradores y congeladores que requieren vidrio templado",
    "configuracion": "Monolítico (para DGU/TGU)",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Neutro (transparente)",
    "tl": "Alta",
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": "Baja",
    "ref_int": null,
    "norma": "EN1096",
    "templable": "SI (diseñado para templar)",
    "laminable": "NO",
    "dgu": "ES_COMPONENTE_DGU",
    "aplicaciones": "Refrigeradores verticales; vitrinas refrigeradas; puertas de refrigerador industrial",
    "beneficios": "Versión templable del Planitherm; 17% mayor ahorro vs Low-E convencional; anti-condensación; color neutro; alta seguridad",
    "necesidad": "Instalación de refrigeración donde se requiere vidrio templado (seguridad) además de alto aislamiento térmico",
    "pitch": "Planitherm UN II: cuando la normativa exige vidrio templado en refrigeración. La versión de seguridad del Planitherm ONE. Mayor costo pero cumple estándares de seguridad industrial.",
    "notas": "Diseñado específicamente para templar. Capa en cara 2 o 3. Cumple EN1096. Amigable con el ambiente.",
    "url": "https://www.mx.saint-gobain-glass.com/products/planitherm-un-ii"
  },
  {
    "nombre": "Satinovo 1C",
    "familia": "Decorativo / Satinado",
    "slug": "satinovo-1c",
    "desc": "Vidrio satinado en una cara. Alta luz difusa con privacidad. Fácil limpieza.",
    "segmento": "Residencial / Comercial / Decorativo",
    "aplicacion_principal": "Cabinas de ducha, puertas, divisiones, mobiliario",
    "configuracion": "Monolítico / Laminable / Templable",
    "espesor_mm": "N/D",
    "dimensiones_max_mm": "N/D",
    "color": "Satinado",
    "tl": 75,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "N/D",
    "templable": "SI",
    "laminable": "SI",
    "dgu": "SI",
    "aplicaciones": "Cabinas de ducha; puertas; balcones; revestimientos; puertas deslizantes; escalones; ventanas; muebles de baño y cocina",
    "beneficios": "Privacidad con luz difusa; fácil limpieza; no deja marcas de huellas; versátil en procesamiento; disponible en color (base Parsol)",
    "necesidad": "Interior que requiere privacidad con luz natural difusa y estética moderna en duchas, oficinas o mobiliario",
    "pitch": "Satinovo 1C: la solución estética para interiores modernos. Privacidad sin oscuridad. Se puede limpiar fácilmente y procesar igual que el flotado convencional.",
    "notas": "Tratamiento satinado en una cara. Disponible sobre SGG Planilux o SGG Parsol (colores). Templable, laminable, biselable.",
    "url": "https://www.mx.saint-gobain-glass.com/products/satinovo-1c"
  },
  {
    "nombre": "Satinovo Duo",
    "familia": "Decorativo / Satinado",
    "slug": "satinovo-duo",
    "desc": "Vidrio satinado en ambas caras. Mayor privacidad y efecto único. 3-12mm.",
    "segmento": "Residencial / Comercial / Decorativo",
    "aplicacion_principal": "Puertas, divisiones y mobiliario con máxima privacidad",
    "configuracion": "Monolítico",
    "espesor_mm": "3-12",
    "dimensiones_max_mm": "3210x2000-2400",
    "color": "Satinado (ambas caras)",
    "tl": 70,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "N/D",
    "ref_ext": null,
    "ref_int": null,
    "norma": "N/D",
    "templable": "NO",
    "laminable": "NO",
    "dgu": "NO",
    "aplicaciones": "Puertas; balcones; revestimientos; puertas deslizantes; escalones; ventanas; muebles de baño y cocina; tabiques",
    "beneficios": "Máxima privacidad (ambas caras); luz difusa uniforme; efecto decorativo único; no deja marcas de huellas; bajo mantenimiento; pureza de color",
    "necesidad": "Interior de alta privacidad donde el tratamiento en ambas caras crea un efecto estético especial",
    "pitch": "Satinovo Duo: para proyectos donde una cara no es suficiente. Tratamiento en ambas caras da máxima privacidad y un efecto de luz purísimo. Para divisiones y mobiliario de diseño.",
    "notas": "Espesores: 3,4,5,6,8,10,12mm. Dimensiones: 3210x2000mm y 3210x2400mm. No templable. No recomendado como elemento estructural.",
    "url": "https://www.mx.saint-gobain-glass.com/products/satinovo-duo"
  },
  {
    "nombre": "Timeless",
    "familia": "Funcional / Bajo Mantenimiento",
    "slug": "timeless",
    "desc": "Vidrio anti-corrosión para canceles de ducha. Capa invisible evita manchas blancas.",
    "segmento": "Residencial",
    "aplicacion_principal": "Canceles y mamparas de baño",
    "configuracion": "Monolítico",
    "espesor_mm": "6 / 10",
    "dimensiones_max_mm": "6100x3300 / 3300x2600",
    "color": "Incoloro / Claro neutro",
    "tl": 89,
    "shgc": null,
    "sc": null,
    "sel": null,
    "u": "5.8",
    "ref_ext": 8,
    "ref_int": 8,
    "norma": "N/D",
    "templable": "SI",
    "laminable": "NO",
    "dgu": "NO",
    "aplicaciones": "Canceles de baño; mamparas de ducha",
    "beneficios": "Previene manchas blancas de cal y corrosión; bajo mantenimiento; transparencia excepcional; sin tinte; capa invisible; larga vida útil",
    "necesidad": "Cancel de ducha que siempre está manchado de cal y agua y requiere limpieza constante",
    "pitch": "Timeless: el cancel de baño que se mantiene impecable sin esfuerzo. La capa mineral invisible repele el agua y el jabón. Para casas de lujo y hoteles donde el mantenimiento es costoso.",
    "notas": "Capa mineral hidrofóbica en cara interior del cancel. Disponible en 6mm y 10mm. Dimensiones estándar: 6.10x3.30m y 3.30x2.60m. Transparencia igual a Planilux.",
    "url": "https://www.mx.saint-gobain-glass.com/products/timeless"
  }
];
